const Constants={

    FETCH_POPULAR_MOVIES_REQUEST : 'FETCH_POPULAR_MOVIES_REQUEST',
    FETCH_POPULAR_MOVIES_SUCCESS : 'FETCH_POPULAR_MOVIES_SUCCESS',
    FETCH_POPULAR_MOVIES_FAIL : 'FETCH_POPULAR_MOVIES_FAIL',

    FETCH_TRENDING_MOVIES_REQUEST : 'FETCH_TRENDING_MOVIES_REQUEST',
    FETCH_TRENDING_MOVIES_SUCCESS : 'FETCH_TRENDING_MOVIES_SUCCESS',
    FETCH_TRENDING_MOVIES_FAIL : 'FETCH_TRENDING_MOVIES_FAIL',

    FETCH_MOVIES_CAST_REQUEST : 'FETCH_MOVIES_CAST_REQUEST',
    FETCH_MOVIES_CAST_SUCCESS : 'FETCH_MOVIES_CAST_SUCCESS',
    FETCH_MOVIES_CAST_FAIL : 'FETCH_MOVIES_CAST_FAIL',

    FETCH_SEARCH_MOVIES_REQUEST : 'FETCH_SEARCH_MOVIES_REQUEST',
    FETCH_SEARCH_MOVIES_SUCCESS : 'FETCH_SEARCH_MOVIES_SUCCESS',
    FETCH_SEARCH_MOVIES_FAIL : 'FETCH_SEARCH_MOVIES_FAIL',

    FETCH_MOVIES_ID_REQUEST : 'FETCH_SELECTED_MOVIES_REQUEST',
    FETCH_MOVIES_ID_SUCCESS : 'FETCH_SELECTED_MOVIES_SUCCESS',
    FETCH_MOVIES_ID_FAIL : 'FETCH_SELECTED_MOVIES_FAIL'
   
   }
   
   export default Constants;